"""Selectable spoken languages of a lecture and their Whisper codes (ADR-0040).

The list lives in `asr.languages_file` (generated by tools/gen_languages, edited by hand only to move a
language between tiers). It is validated when an entry point starts; a bad file stops startup.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any

import yaml

TIERS = ("tested", "untested")
TIER_LABELS = {"tested": "Tested", "untested": "Not tested — transcription quality unknown"}
_FIELDS = {"id", "label", "whisper_language", "tier", "evidence"}


class LanguageConfigError(Exception):
    """The language file is missing, unreadable or invalid. The message names the file and the problem."""


@dataclass(frozen=True)
class Language:
    id: str
    label: str
    whisper_language: str
    tier: str
    evidence: str | None = None

    def public(self) -> dict[str, str]:
        """What the API and UI show: id, label, tier."""
        return {"id": self.id, "label": self.label, "tier": self.tier}


@dataclass(frozen=True)
class Languages:
    entries: tuple[Language, ...]

    def get(self, language_id: str) -> Language | None:
        return next((e for e in self.entries if e.id == language_id), None)

    def grouped(self) -> list[dict[str, Any]]:
        """Tested first, then untested; each group sorted by label (case-insensitive)."""
        return [
            {"tier": tier, "label": TIER_LABELS[tier],
             "languages": [e.public() for e in sorted((e for e in self.entries if e.tier == tier),
                                                      key=lambda e: e.label.casefold())]}
            for tier in TIERS
        ]


def supported_whisper_codes() -> frozenset[str]:
    """Language codes of the installed faster-whisper (the multilingual tokenizer's list)."""
    from faster_whisper.tokenizer import _LANGUAGE_CODES

    return frozenset(_LANGUAGE_CODES)


def parse_languages(data: Any, supported: frozenset[str], source: str = "language config") -> Languages:
    """Validate the parsed YAML; raise LanguageConfigError listing every problem."""
    if not isinstance(data, dict) or not isinstance(data.get("languages"), list) or not data["languages"]:
        raise LanguageConfigError(f"{source}: expected a non-empty 'languages:' list")
    problems: list[str] = []
    entries: list[Language] = []
    seen: set[str] = set()
    for i, raw in enumerate(data["languages"]):
        where = f"entry {i + 1}"
        if not isinstance(raw, dict):
            problems.append(f"{where}: not a mapping")
            continue
        where = f"entry {i + 1} ({raw.get('id')!r})"
        unknown = set(raw) - _FIELDS
        if unknown:
            problems.append(f"{where}: unknown keys {sorted(unknown)}")
        missing = [k for k in ("id", "label", "whisper_language", "tier") if not isinstance(raw.get(k), str) or not raw[k]]
        if missing:
            problems.append(f"{where}: missing or non-text {missing}")
            continue
        lang_id, tier, code, evidence = raw["id"], raw["tier"], raw["whisper_language"], raw.get("evidence")
        if lang_id != lang_id.lower() or not lang_id.replace("_", "").isalnum():
            problems.append(f"{where}: id must be lowercase letters, digits and underscores")
        if lang_id in seen:
            problems.append(f"{where}: duplicate id {lang_id!r}")
        seen.add(lang_id)
        if tier not in TIERS:
            problems.append(f"{where}: tier must be one of {TIERS}, got {tier!r}")
        if code not in supported:
            problems.append(f"{where}: whisper_language {code!r} is not supported by the installed faster-whisper")
        if tier == "tested" and not (isinstance(evidence, str) and evidence.strip()):
            problems.append(f"{where}: a tested language needs 'evidence' (the ADR with its WER gate)")
        if tier == "untested" and evidence is not None:
            problems.append(f"{where}: an untested language must not have 'evidence'")
        entries.append(Language(lang_id, raw["label"], code, tier, evidence))
    if problems:
        raise LanguageConfigError(f"{source} is invalid:\n  " + "\n  ".join(problems))
    return Languages(tuple(entries))


def load_languages(path: Path, supported: frozenset[str] | None = None) -> Languages:
    """Read and validate the language file. Raises LanguageConfigError."""
    try:
        data = yaml.safe_load(Path(path).read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError) as exc:
        raise LanguageConfigError(f"cannot read language config {path}: {exc}") from exc
    return parse_languages(data, supported if supported is not None else supported_whisper_codes(), str(path))


@lru_cache(maxsize=4)
def _cached(path: str, mtime_ns: int) -> Languages:
    return load_languages(Path(path))


def languages_for(settings) -> Languages:
    """The validated languages of `settings.asr.languages_file`, re-read when the file changes."""
    path = settings.asr.languages_file
    try:
        mtime = path.stat().st_mtime_ns
    except OSError as exc:
        raise LanguageConfigError(f"cannot read language config {path}: {exc}") from exc
    return _cached(str(path), mtime)


def require_language(settings, value: Any):
    """The language entry for a submitted id. Raises IngestError(MISSING_LANGUAGE | UNKNOWN_LANGUAGE).

    Called before anything is staged or queued, so a bad request leaves nothing behind.
    """
    from insightex.ingest.errors import ErrorCode, IngestError

    if value is None or (isinstance(value, str) and not value.strip()):
        raise IngestError(ErrorCode.MISSING_LANGUAGE)
    entry = languages_for(settings).get(value) if isinstance(value, str) else None
    if entry is None:
        shown = value if isinstance(value, str) and len(value) <= 64 else "(invalid value)"
        raise IngestError(
            ErrorCode.UNKNOWN_LANGUAGE,
            f"\"{shown}\" isn't one of the listed lecture languages. Choose a language from the list "
            f"(see GET /api/languages or `insightex languages list`) and add the lecture again.",
        )
    return entry
