"""Generate config/languages.yaml: every spoken language the installed faster-whisper supports (ADR-0040).

Run once per faster-whisper upgrade and commit the result, so the selectable list never changes silently:

    bash ~/insightex/scripts/run_in_env.sh python ~/insightex/tools/gen_languages/gen_languages.py \
        --out ~/insightex/config/languages.yaml

The tested entries are fixed below. Every other Whisper code becomes one untested entry with an English label.
Hindi exists only as its tested entry (Whisper code `ur`), so the code `hi` gets no entry of its own.
Standalone: no imports from backend/.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# English names of Whisper's language codes, from openai/whisper `whisper/tokenizer.py` (LANGUAGES), title-cased.
NAMES = {
    "en": "english", "zh": "chinese", "de": "german", "es": "spanish", "ru": "russian", "ko": "korean",
    "fr": "french", "ja": "japanese", "pt": "portuguese", "tr": "turkish", "pl": "polish", "ca": "catalan",
    "nl": "dutch", "ar": "arabic", "sv": "swedish", "it": "italian", "id": "indonesian", "hi": "hindi",
    "fi": "finnish", "vi": "vietnamese", "he": "hebrew", "uk": "ukrainian", "el": "greek", "ms": "malay",
    "cs": "czech", "ro": "romanian", "da": "danish", "hu": "hungarian", "ta": "tamil", "no": "norwegian",
    "th": "thai", "ur": "urdu", "hr": "croatian", "bg": "bulgarian", "lt": "lithuanian", "la": "latin",
    "mi": "maori", "ml": "malayalam", "cy": "welsh", "sk": "slovak", "te": "telugu", "fa": "persian",
    "lv": "latvian", "bn": "bengali", "sr": "serbian", "az": "azerbaijani", "sl": "slovenian", "kn": "kannada",
    "et": "estonian", "mk": "macedonian", "br": "breton", "eu": "basque", "is": "icelandic", "hy": "armenian",
    "ne": "nepali", "mn": "mongolian", "bs": "bosnian", "kk": "kazakh", "sq": "albanian", "sw": "swahili",
    "gl": "galician", "mr": "marathi", "pa": "punjabi", "si": "sinhala", "km": "khmer", "sn": "shona",
    "yo": "yoruba", "so": "somali", "af": "afrikaans", "oc": "occitan", "ka": "georgian", "be": "belarusian",
    "tg": "tajik", "sd": "sindhi", "gu": "gujarati", "am": "amharic", "yi": "yiddish", "lo": "lao",
    "uz": "uzbek", "fo": "faroese", "ht": "haitian creole", "ps": "pashto", "tk": "turkmen", "nn": "nynorsk",
    "mt": "maltese", "sa": "sanskrit", "lb": "luxembourgish", "my": "myanmar", "bo": "tibetan", "tl": "tagalog",
    "mg": "malagasy", "as": "assamese", "tt": "tatar", "haw": "hawaiian", "ln": "lingala", "ha": "hausa",
    "ba": "bashkir", "jw": "javanese", "su": "sundanese", "yue": "cantonese",
}

TESTED = [
    {"id": "hindi", "label": "Hindi (including Hindi-English mixed)", "whisper_language": "ur", "tier": "tested",
     "evidence": "ADR-0039"},
]
EXCLUDED_CODES = {"hi"}  # Hindi is the tested entry above


def _id(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


def _q(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def build(codes: list[str], version: str) -> str:
    missing = [c for c in codes if c not in NAMES]
    if missing:
        raise SystemExit(f"no English name for Whisper codes {missing}; add them to NAMES")
    untested = sorted(
        ({"id": _id(NAMES[c]), "label": NAMES[c].title(), "whisper_language": c} for c in codes if c not in EXCLUDED_CODES),
        key=lambda e: e["label"],
    )
    lines = [
        "# Selectable spoken languages of a lecture (ADR-0040). GENERATED by tools/gen_languages/gen_languages.py",
        f"# from faster-whisper {version} ({len(codes)} codes); regenerate only on a faster-whisper upgrade and review the diff.",
        "# Edit by hand only to move a language between tiers or change its whisper_language (no code change needed).",
        "# id: stable key stored in jobs; label: English display name; whisper_language: code passed to Whisper;",
        "# tier: tested (passed a WER gate; evidence names the ADR) or untested (no evidence key).",
        "languages:",
    ]
    for e in TESTED:
        lines += [f"  - id: {e['id']}", f"    label: {_q(e['label'])}", f"    whisper_language: {e['whisper_language']}",
                  f"    tier: {e['tier']}", f"    evidence: {e['evidence']}"]
    for e in untested:
        lines += [f"  - id: {e['id']}", f"    label: {_q(e['label'])}", f"    whisper_language: {_q(e['whisper_language'])}",
                  "    tier: untested"]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, help="path of the languages YAML to write")
    a = ap.parse_args()
    import faster_whisper
    from faster_whisper.tokenizer import _LANGUAGE_CODES

    text = build(list(_LANGUAGE_CODES), faster_whisper.__version__)
    Path(a.out).expanduser().write_text(text, encoding="utf-8")
    print(f"wrote {a.out}: {len(TESTED)} tested, {len(_LANGUAGE_CODES) - len(EXCLUDED_CODES)} untested")
    return 0


if __name__ == "__main__":
    sys.exit(main())
